# Generated by Django 4.0.4 on 2022-05-22 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contactus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('emailadress', models.CharField(max_length=100)),
                ('phonenumber', models.CharField(max_length=100)),
                ('messages', models.CharField(max_length=2000)),
            ],
            options={
                'db_table': 'Contactus',
            },
        ),
    ]
