# Generated by Django 4.0.4 on 2022-05-23 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='houses',
            name='areaofhouse',
        ),
        migrations.AddField(
            model_name='houses',
            name='lengthofhouse',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='houses',
            name='widthofhouse',
            field=models.IntegerField(default=1),
        ),
    ]
