# Generated by Django 4.0.4 on 2022-05-23 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_remove_houses_areaofhouse_houses_lengthofhouse_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='houses',
            name='description',
            field=models.CharField(default='A four bedroom house, near the river, good security, school is 100m away and hospital 1.5km away', max_length=7000),
        ),
    ]
