# Generated by Django 4.0.4 on 2022-05-23 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_houses_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='houses',
            name='description',
            field=models.CharField(default='No description', max_length=7000),
        ),
    ]
