# Generated by Django 4.0.4 on 2022-05-23 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_alter_houses_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('useremails', models.CharField(max_length=100)),
                ('telephoneno', models.CharField(max_length=100)),
                ('availabilitymessage', models.CharField(max_length=990)),
            ],
            options={
                'db_table': 'Availability',
            },
        ),
        migrations.AddField(
            model_name='houses',
            name='choices',
            field=models.CharField(choices=[(1, 'Single-Family Homes'), (2, 'Semi-Detached Home'), (3, 'Multifamily Homes'), (4, 'Townhomes'), (5, 'Apartments'), (6, 'Condominiums'), (7, 'Co-Ops'), (8, 'Tiny Home '), (9, 'Mobile Home')], default=2, max_length=100),
        ),
    ]
